name: BraneBuild
on: ['push']

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check out cargo code
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'install brane with cargo'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git http://github.com/onnovalkering/brane brane-cli

      - name: 'test the brane package'
        run: |
          brane build ./container.yml

      - name: 'build package'
        run: |
          brane import
