name: CI
on: ['push']

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check out cargo code
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'install cargo'
        run: cargo build --release --all-features

      - name: 'install brane'
        run: cargo install --git http://github.com/onnovalkering/brane brane-cli

      - name: 'use the brane CLI'
        run: |
          brane --help
          # check that the brane services are running
          docker ps

      - name: 'query the jupyterlab IDE access token'
        run: |
          echo "${{ steps.brane_setup.outputs.jupyterlab_token }}"